services:
  invoicen_ayushchugh_com_nextjs:
    image: invoicen.ayushchugh.com
    container_name: invoicen.ayushchugh.com
    working_dir: /app
    ports:
      - "3008:3000"
    expose:
      - "3000"
    command: "npm start"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
